name: Run Task

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ... otros pasos ...

      - name: Running
        run: |
          npm cache clean --force
          npm install
          npm run task
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_API: ${{ secrets.BOT_API }}

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update db.json
          branch: main
